### ISSUE TITLE
複数クラスでのサウンド反応に関しての質問

### ISSUE THREAD

**Issue by JunNishimura** [JunNishimura/vjSetForAugust#1]
お忙しいと思うので、時間がある時にでも答えて頂けると嬉しいです。

Soundに反応させるのは,ofSoundStreamとかaudioInとか使えばいいのはわかっているのですが、今回のように複数のクラスで音に反応させようと思った場合は、ofSoundStreamやaudioInをどこに書けばいいのかで悩んでいます。(ofAppに書いて各シーンに引っ張ってくるのか、各シーンで毎回書くのかなど)

普通に、他クラスをofAppでincludeしてやるなら、ofApp内に書けばいいと思うのですが、今回の場合、ofAppからシーン切り替えで各シーンに飛んで、映像を出す感じなので。

急ぎではないので、お時間がある時にでもお願いします。

**Comment by Hiroki11x** [comment]
@JunNishimura お返事遅くなりました！
Singleton Pattern というキーワードで概念を理解してみてください！
コードとしてはこの辺りが参考になるかも

http://qiita.com/kikuuuty/items/fcf5f7df2f0493c437dc

**Comment by JunNishimura** [comment]
お忙しい中ありがとうございます！
singleton pattern勉強します！
それでは世界大会頑張ってください！応援しています！！
